In [20]:
import numpy as np
from scipy.signal import convolve2d

x = np.array([[-1,-1],
              [ 1 ,1]])

y = np.array([[1, 1],
              [-1,-1]])
z = np.ones((2,2))

convolve2d(x, y)

array([[-1, -2, -1],
       [ 2,  4,  2],
       [-1, -2, -1]])

In [21]:

convolve2d(y, x)

array([[-1, -2, -1],
       [ 2,  4,  2],
       [-1, -2, -1]])

In [6]:
convolve2d(y,z), convolve2d(z,y)

(array([[ 1.,  1.,  0., -1., -1.],
        [ 2.,  2.,  0., -2., -2.],
        [ 3.,  3.,  0., -3., -3.],
        [ 2.,  2.,  0., -2., -2.],
        [ 1.,  1.,  0., -1., -1.]]),
 array([[ 1.,  1.,  0., -1., -1.],
        [ 2.,  2.,  0., -2., -2.],
        [ 3.,  3.,  0., -3., -3.],
        [ 2.,  2.,  0., -2., -2.],
        [ 1.,  1.,  0., -1., -1.]]))